UserAuth/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.conf import settings
# from django.conf.urls.static import static
from dashboard import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login3'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from dashboard.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

dashboard/views.py
from django.shortcuts import render
from dashboard.forms import UserForm,UserProfileInfoForm
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login , logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request,'dashboard/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("you are logged in !")


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(request.POST,request.FILES)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            #if 'profile_pics' in request.FILES:
            #    profile.profile_pic = request.FILES['profile_pics']

            profile.save()

            registered = True
            return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'dashboard/registration.html',{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})


def user_login(request):

    if request.method == "POST":
        username1 = request.POST.get('username')
        password1= request.POST.get('password')

        user = authenticate(username=username1,password=password1)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active!")

        else:
            # print("someone tried to login and failed!")
            # print("username: {} and password: {}".format(username1,password1))
            return HttpResponse("Invalid login details supplied for {}".format(username1))
    else:
        return render(request,'dashboard/login.html')

templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class = "nav navbar-nav">
          <li><a href="{% url 'index' %}" class='navbar-brand'>DJANGO</a></li>
          <li><a href="{% url 'admin:index' %}" class='navbar-link'>Admin</a></li>
          {% if user.is_authenticated %}
           <li><a href="{% url 'logout' %}" class='navbar-link'>logout</a></li>
           {% else %}
           <li><a href="{% url 'dashboard:register' %}" class='navbar-link'>Register</a></li>
           <li><a href="{% url 'dashboard:user_login3' %}" class='navbar-link'>login</a></li>
           {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/dashboard/index.html
<!DOCTYPE html>
{% extends "dashboard/base.html"%}
{% block body_block %}
<div class="jumbotron">
  <h1>django level five!</h1>
</div>

{% endblock%}

templates/dashboard/login.html
{% extends 'dashboard/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login!</h1>
  <form  action="{% url 'dashboard:user_login3' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username...">
    <label for="password" >password:</label>
    <input type="password" name="password" >
    <input type="submit" name="" value="login">
  </form>
</div>

{% endblock %}

templates/dashboard/registration.html
<!DOCTYPE html>
{% extends "dashboard/base.html"%}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if user.is_authenticated %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h1>register here!</h1>
  <h2>Fll out the form</h2>

 <form  enctype="multipart/form-data"  method="post">
   {% csrf_token %}
   {{ user_form.as_p }}
   {{ profile_form.as_p }}
   <input type="submit" name="" value="register">
 </form>


  {% endif %}
</div>

{% endblock%}